server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: order-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/orders_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

otel:
  service:
    name: order-service
    version: 0.1.0
